import GooddoerFactory from "../abi/GooddoerFactory.json";

const GOODDOER_FACTORY_CONTRACT_ADDRESS =
	"0x35197AD5AF1E4EF87A89649A819C1Dc4D00aB1F5";
const GOODDOER_FACTORY_ABI = GooddoerFactory.abi;

export { GOODDOER_FACTORY_CONTRACT_ADDRESS, GOODDOER_FACTORY_ABI };
